In [ ]:
# NumPy : 파이썬에서 수학과 데이터 분석을 쉽게 할 수 있도록 도와주는 라이브러리
# ndArray : 숫자를 여러 차원으로 저장할 수 있는 배열
# NumPy로 할 수 있는 것들
# - 숫자 묶음 생성
# - 평균, 합계, 최대값
# - 배열 덧셈, 곱셈
# - 2차원 표(행렬)

In [ ]:
# 일반 리스트
a = [1, 2, 3]
b = [4, 5, 6]

a + b

[1, 2, 3, 4, 5, 6]

In [4]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
# np.array([1, 2, 3]) => 리스트 처럼 보이지만 실제로는 수학용 배열, 모든 원소가 같은 타입

a + b

array([5, 7, 9])

In [ ]:
import numpy as np

# 1차원 ndArray 생성(숫자 4개가 한 줄로 있는 배열)
np.array([1, 2, 3, 4])

arr1 = np.array([1, 2, 3, 4]) # numpy 배열임을 알려줌
arr2 = [1, 2, 3, 4] # 일반 리스트

# <class 'numpy.ndarray'>
# 넘파이로 이루어진 다차원 배열
print(type(arr1))

# <class 'list'>
# 파이썬 리스트 형태
print(type(arr2))

<class 'numpy.ndarray'>
<class 'list'>


In [6]:
# 1차원 배열 : 숫자가 한 줄로 늘어선 형태
# 2차원 배열 : 숫자가 가로와 세로로 된 표 모양
# 3차원 배열 : 2차원 배열이 여러장 겹친 입체 모양

# 2차원 ndArray 생성
# 1차원 배열 두개가 리스트로 묶인 형태 2차원 배열이다.
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8]])

arr3 = np.array([[[1, 2, 3, 4], [1, 2, 3, 4]],
                [[1, 2, 3, 4], [1, 2, 3, 4]]])


print("2차원 배열 arr2")
print(arr2)

print("3차원 배열 arr3")
print(arr3)

2차원 배열 arr2
[[1 2 3 4]
 [5 6 7 8]]
3차원 배열 arr3
[[[1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]]]
