In [ ]:
# NumPy : 파이썬에서 수학과 데이터 분석을 쉽게 할 수 있도록 도와주는 라이브러리
# ndArray : 숫자를 여러 차원으로 저장할 수 있는 배열
# NumPy로 할 수 있는 것들
# - 숫자 묶음 생성
# - 평균, 합계, 최대값
# - 배열 덧셈, 곱셈
# - 2차원 표(행렬)

In [ ]:
# 일반 리스트
a = [1, 2, 3]
b = [4, 5, 6]

a + b

[1, 2, 3, 4, 5, 6]

In [4]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
# np.array([1, 2, 3]) => 리스트 처럼 보이지만 실제로는 수학용 배열, 모든 원소가 같은 타입

a + b

array([5, 7, 9])

In [ ]:
import numpy as np

# 1차원 ndArray 생성(숫자 4개가 한 줄로 있는 배열)
np.array([1, 2, 3, 4])

arr1 = np.array([1, 2, 3, 4]) # numpy 배열임을 알려줌
arr2 = [1, 2, 3, 4] # 일반 리스트

# <class 'numpy.ndarray'>
# 넘파이로 이루어진 다차원 배열
print(type(arr1))

# <class 'list'>
# 파이썬 리스트 형태
print(type(arr2))

<class 'numpy.ndarray'>
<class 'list'>


In [6]:
# 1차원 배열 : 숫자가 한 줄로 늘어선 형태
# 2차원 배열 : 숫자가 가로와 세로로 된 표 모양
# 3차원 배열 : 2차원 배열이 여러장 겹친 입체 모양

# 2차원 ndArray 생성
# 1차원 배열 두개가 리스트로 묶인 형태 2차원 배열이다.
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8]])

arr3 = np.array([[[1, 2, 3, 4], [1, 2, 3, 4]],
                [[1, 2, 3, 4], [1, 2, 3, 4]]])


print("2차원 배열 arr2")
print(arr2)

print("3차원 배열 arr3")
print(arr3)

2차원 배열 arr2
[[1 2 3 4]
 [5 6 7 8]]
3차원 배열 arr3
[[[1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]]]


In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4])

print(a + 1)
print(a * 2)
print(a ** 2)
# for문을 안 쓰고도 계산이 가능하다.

[2 3 4 5]
[2 4 6 8]
[ 1  4  9 16]


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])

arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8]])

arr3 = np.array([[[0.1, 0.2, 0.3, 0.4], [1, 2, 3, 4]],
                [[1, 2, 3, 4], [1, 2, 3, 4]]])

# ndim : 배열의 차원 수
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

# shape : 배열의 형태(배열 구조를 튜플로 보여줌)
# (층 개수, 행 개수, 열 개수)
print(arr1.shape) # 숫자 4개가 있는 한 줄
print(arr2.shape) # 2줄, 각 줄에 4칸
print(arr3.shape) # 2장(층), 각 장마다 2줄, 각 줄에 4칸

# size : 배열 요소의 총 개수
print(arr1.size) # 4
print(arr2.size) # 2 * 4 = 8
print(arr3.size) # 2 * 2 * 4 = 16

# dtype : 배열 요소의 데이터 타입
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

# itemsize : 배열 원소 하나가 차지하는 메모리 크기
print(arr1.itemsize)
print(arr2.itemsize)
print(arr3.itemsize)

# data : 배열의 실제 데이터가 저장된 메모리 버퍼(buffer 주소)
print(arr1.data)
print(arr2.data)
print(arr3.data)

1
2
3
(4,)
(2, 4)
(2, 2, 4)
4
8
16
int64
int64
float64
8
8
8


In [13]:
# ndarray.T : 전치 행렬(행/열을 서로 바꾸는 것)
arr = np.array([[1,2,3],
               [4,5,6]])

print("원래 배열")
print(arr)

print("전치 배열")
print(arr.T)

원래 배열
[[1 2 3]
 [4 5 6]]
전치 배열
[[1 4]
 [2 5]
 [3 6]]


In [18]:
# ndArray.flatten() : 1차원으로 펼치기
arr = np.array([[1,2,3],
               [4,5,6]])

print("원래 배열")
print(arr)

print("1차원으로 펼친 배열")
print(arr.flatten())

# flatten()은 복사본(copy)를 만든다.
flat = arr.flatten()
flat[0] = 100

print("== 배열 출력 ==")
print(arr)

원래 배열
[[1 2 3]
 [4 5 6]]
1차원으로 펼친 배열
[1 2 3 4 5 6]
== 배열 출력 ==
[[1 2 3]
 [4 5 6]]


In [ ]:
# ndArray.reshape() : 배열 모양 바꾸기
arr = np.array([1, 2, 3, 4, 5, 6])

print("원래 배열")
print(arr)

# reshape 할 땐 원본과 size가 같아야 한다.
arr2 = arr.reshape(2, 3) # 2행 3열로 반환
print("reshape 배열")
print(arr2)

원래 배열
[1 2 3 4 5 6]
reshape 배열
[[1 2 3]
 [4 5 6]]


In [33]:
# ndArray.sum() : 합계 구하기
# axis : 어느 축을 기준으로 계산할 것인가
# axis 옵션
# axis=0 : 열(세로 축) 방향 합
# axis=1 : 행(가로 축) 방향 합

arr = np.array([[1,2,3],
               [4,5,6]])

print("전체 합 :", arr.sum())

print("열 방향 합(axis=0) :", arr.sum(axis=0))
print("행 방향 합(axis=1) :", arr.sum(axis=1))

전체 합 : 21
열 방향 합(axis=0) : [5 7 9]
행 방향 합(axis=1) : [ 6 15]


In [34]:
# ndArray.mean() : 평균 구하기
# axis 옵션
# axis=0 : 열(세로 축) 방향 합
# axis=1 : 행(가로 축) 방향 합

arr = np.array([[1,2,3],
               [4,5,6]])

print("전체 평균 :", arr.mean())

print("열 방향 평균(axis=0) :", arr.mean(axis=0))
print("행 방향 평균(axis=1) :", arr.mean(axis=1))

전체 평균 : 3.5
열 방향 평균(axis=0) : [2.5 3.5 4.5]
행 방향 평균(axis=1) : [2. 5.]


In [38]:
# ndArray.min() : 최솟값 구하기
# ndArray.max() : 최댓값 구하기
# axis 옵션
# axis=0 : 열(세로 축) 방향 합
# axis=1 : 행(가로 축) 방향 합

arr = np.array([[1,2,3],
               [4,5,6]])

print("전체 최솟값 :", arr.min())
print("전체 최댓값 :", arr.max())

print("열 방향 최솟값(axis=0) :", arr.min(axis=0))
print("열 방향 최댓값(axis=0) :", arr.max(axis=0))

print("행 방향 최솟값(axis=1) :", arr.min(axis=1))
print("행 방향 최댓값(axis=1) :", arr.max(axis=1))

전체 최솟값 : 1
전체 최댓값 : 6
열 방향 최솟값(axis=0) : [1 2 3]
열 방향 최댓값(axis=0) : [4 5 6]
행 방향 최솟값(axis=1) : [1 4]
행 방향 최댓값(axis=1) : [3 6]
