In [10]:
import numpy as np

arr = np.array([[1.5, 2.5, 3.5, 4.5],
                [5.5, 6.5, 7.5, 8.5]])

# 문제
# 1. arr의 dtype과 itemsize를 출력하시오.
print("dtype :", arr.dtype)
print("itemsize :", arr.itemsize)

# 2. axis=0 기준 합을 구하시오.
print("열 방향 합 :", arr.sum(axis=0))

# 3. axis=1 기준 평균을 구하시오.
print("행 방향 평균 :", arr.mean(axis=1))

# 4. arr을 (4,2) 형태로 reshape 하시오.
arr_reshape =  arr.reshape(4, 2)
print("reshape (4, 2) :")
print(arr_reshape)

# 5. reshape한 배열을 전치한 결과의 shape을 구하시오.
print("전치 arr_reshape :")
print(arr_reshape.T)
print("전치 arr_reshape shape :", arr_reshape.T.shape)

# 6. arr.flatten()으로 만든 배열의 shape은 무엇인가?
print("flatten shape :", arr.flatten().shape)

dtype : float64
itemsize : 8
열 방향 합 : [ 7.  9. 11. 13.]
행 방향 평균 : [3. 7.]
reshape (4, 2) :
[[1.5 2.5]
 [3.5 4.5]
 [5.5 6.5]
 [7.5 8.5]]
전치 arr_reshape :
[[1.5 3.5 5.5 7.5]
 [2.5 4.5 6.5 8.5]]
전치 arr_reshape shape : (2, 4)
flatten shape : (8,)
