In [ ]:
import numpy as np

np.random.seed(1)
# -10 ~10 사이의 정수로 (3,4) 모양의 배열을 만들고 arr1에 저장
arr1 = np.random.randint(-10, 11, (3, 4)) # 3 x 4

# 아래와 같은 2차원 배열을 만들고 arr2에 저장
# 1,2,3,4
# 5,6,7,8
# 9,10,11,12
# 13,14,15,16
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]]) # 4 x 4

# 1. 각 배열의 차원, 모양, 원소의 개수를 확인
print(arr1.ndim)
print(arr2.ndim)

print(arr1.shape)
print(arr2.shape)

print(arr1.size)
print(arr2.size)

# 2. arr1에서 행은 모두 출력하고 열은 첫번째, 세번째만 출력
print('arr1')
print(arr1)
print('arr2')
print(arr2)
print(arr1[::, :3:2])
# :: => 행 => 처음부터 끝까지 전부
# :3:2 => 열 => 0번부터 3번 직전까지, 그 중에서 간격(step) = 0, 2 선택

# 3. arr2에서 아래처럼 나오게 인덱싱해주세요
# [6, 7]
# [10, 11]
print(arr2[1:3, 1:3])
# 1:3 => 행 => 행 인덱스 1, 2 선택
# 1:3 => 열 => 열 인덱스 1, 2 선택

# 4. arr1에서 음수만 출력
arr3 = arr1[arr1 < 0]
print(arr3)

2
2
(3, 4)
(4, 4)
12
16
arr1
[[ -5   1   2  -2]
 [ -1   1  -5   5]
 [-10   6  -9   2]]
arr2
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ -5   2]
 [ -1  -5]
 [-10  -9]]
[[ 6  7]
 [10 11]]
[ -5  -2  -1  -5 -10  -9]
